### PR TITLE
Adding MANA and updating token tests

### PR DESCRIPTION
**Pull request by andy8052**
I added the mana token and refactored the token tests to all be in the same function

### CODE REVIEW

**Review by gbalabasquer — APPROVED** [review]
LTGM. Let's wait a bit to merge this though. Want to check if we want to do it now or in the next release.

**Comment by andy8052** [comment]
Sounds good. Do you think I should refactor this to be 2 PRs. With one adding MANA and the other changing the test structure? That way we can get the test change merged and leave MANA as a PR?

**Comment by gbalabasquer** [comment]
Brian applied the same tests change in `tusd` branch, so it's already in master. That is probably why we are having conflicts in this PR now. So let's fix the conflicts in this PR and when we merge using the squash option this final commit will end up being only the mana addendum.

**Comment by gbalabasquer** [comment]
Oops I had forgotten about this PR and early in the morning already added MANA to the tokens file. We could close it.

**Comment by gbalabasquer** [comment]
Closing this as it is an old PR.

**Pull request closed without merging**
