### PR TITLE
Add CalcFab

### PR DESCRIPTION
**Pull request by brianmcmichael**
Adds a calc factory.

This will be useful to have on chain during the collateral onboarding process.

### CODE REVIEW

**Comment by brianmcmichael** [comment]
Should also be added as `CALC_FAB` to the changelog once it's on-chain.

**Review by hexonaut — APPROVED** [review]
LGTM

**Comment by gbalabasquer** [comment]
I'm wondering if we would want to make the `DssDeploy` contract to deploy the calcs instead of having to receive them via param.
So far the existing fabs in this repo were mainly created to be used via the Deployer.
This change would require a bit more of work though. So let me think how complex this change would be not only in this repo but the ones importing it and the scripts.

**Comment by brianmcmichael** [comment]
> I'm wondering if we would want to make the `DssDeploy` contract to deploy the calcs instead of having to receive them via param.
> So far the existing fabs in this repo were mainly created to be used via the Deployer.
> This change would require a bit more of work though. So let me think how complex this change would be not only in this repo but the ones importing it and the scripts.

Discussed this offline. Plan is to add this now for CoB and then update deployment scripts later to use the calc-fab.

**Pull request merged**
