### PR TITLE
Auto-manage nonces

### PR DESCRIPTION
**Pull request by nanexcool**
With this commit, deploying to Goerli works. Tested with Goerli, Kovan and dapp testnet.

Replace any `seth send` with `sethSend` and any `dapp create` with `dappCreate`.

### CODE REVIEW

**Comment by gbalabasquer** [comment]
We actually have #34 solving the same issue. However I see the usage of the temp file a better approach than having to `source` the scripts to get the variables exported (which I had not tested 100% yet). We should only verify if we can use the file in that way using nix. I guess as you are pointing to the absolute `/tmp` path there shouldn't be any problem.

**Comment by asymmetric** [comment]
I'm still in favor of finding out the root cause, rather than complicating our deployment scripts.

**Review by asymmetric — COMMENTED** [review]
I'm still in favor of finding out the root cause, rather than complicating our deployment scripts, but of the two, I like this approach better :)

**Comment by gbalabasquer** [comment]
Closing as there are no more scripts in this repo.

**Pull request closed without merging**
