### PR TITLE
Add DSPause

### PR DESCRIPTION
**Pull request by asymmetric**
Deploys one single pause with authority over everything.

Removes the Mom completely, which should be replicated in  [LineSpell](https://github.com/makerdao/line-spell/pull/1).

### CODE REVIEW

**Review by gbalabasquer — APPROVED** [review]

**Comment by levity** [comment]
We're currently using Mom to set line, Line, chop, duty, & base in the testchain. It seems like we should now set MCD_PAUSE_DELAY = 0 and then call file on the Pause instead, is that right?

**Comment by asymmetric** [comment]
That’s correct (although `file` is called on the Plan rather than on the Pause). @gbalabasquer is going to make the necessary changes to the testchain repo.

**Comment by levity** [comment]
> That’s correct (although `file` is called on the Plan rather than on the Pause). @gbalabasquer is going to make the necessary changes to the testchain repo.

Ah, right, thanks. We also have to make our own changes in dai.js that are specific to our CI tests.

**Comment by levity** [comment]
So, I'm not sure it's as easy as I was hoping. Prior to this change, we were able to call Mom directly to make the changes I mentioned (although it's actually not clear to me how this ever worked, since DssDeploy changed owner and authority). Now it seems like we don't have the authorization to call Pause.plan, because its authority is the chief and its owner is address(0). So are we stuck having to create, lift, and cast spells for every change? /cc @tyler17

**Comment by d-xo** [comment]
Does it work if you lift a lil proxy contract to be the `hat` and then call `pause.plan` through that?

Something like:

```solidity
contract gateway {
    function call(address target, bytes memory data) {
        target.call(data);
    }
}
```

**Comment by gbalabasquer** [comment]
@levity it was working as in the previos version the deployer account was elected as the `hat`, then it had full access to all the contracts.
Now you will have to do something like David mentions. Actually in the latest version you will see this `ds-proxy` variable (`PROXY_DEPLOYER`). This is owned by the deployer account. You could use it, but you will also need to create proxy libraries to change what you need. Remember between `plan` and `exec` you will have to wait for the delay.

**Comment by levity** [comment]
ah, ETH_FROM is the hat... that's what i was missing 💡

wait, if ETH_FROM is the hat, shouldn't I be able to call Pause.plan directly?

**Comment by asymmetric** [comment]
The hat is changed to `PROXY_DEPLOYER` [here](
https://github.com/makerdao/testchain-dss-deployment-scripts/tree/35b4069b0dbe7fde1ebcc063dba7b642f05916ce/base-deploy#L133).

Calls to the pause go from `ETH_FROM` -> `DSProxy` -> `DSPause` ([plan + exec](https://github.com/makerdao/testchain-pause-proxy-actions/blob/master/src/TestchainPauseProxyActions.sol)) -> `Target` -> DSS. 😂

**Comment by d-xo** [comment]
Is there any reason for @levity to not just elect `ETH_FROM` as the `hat` in his tests?

**Comment by asymmetric** [comment]
I don't see any issues with that. The `PROXY_DEPLOYER` seems to be used for the convenience of bundling calls.

**Comment by gbalabasquer** [comment]
The reason about `PROXY_DEPLOYER` in the scripts is the need of getting the exact `now` date to execute `plan` and `exec` at the same time.
If you do not use a proxy, you need to guess a date in the future long enough to have the tx mined. Otherwise it will fail. So if you want to use `ETH_FROM` you will need to pass a future date for `plan`. Then wait for that `date + delay` and then run `exec`.

**Comment by d-xo** [comment]
@gbalabasquer You can call `exec` at any time after the `eta` on the `plan` has passed, why do they need to be bundled into one transaction?

**Comment by levity** [comment]
@xwvvvvwx i think it's not so much about executing both at once, but about getting a value for `era` that won't be rejected by `plan` for being too early

**Comment by d-xo** [comment]
> If you do not use a proxy, you need to guess a date in the future long enough to have the tx mined. 

Thx @levity. I think I got it now, if we're calling `pause.plan` using e.g. `seth`, then we don't know the timestamp of the block that the transaction will be mined in, so have to guess.

This is annoying, I'm totally open to considering interface changes if it would be helpful? 

Reasons for putting `eta` in the interface were:

1. Protection against replay attacks (an attacker could intercept the `plan` tx and then submit it at a later date when it's advantageous for them. Not 100% sure this attack is worth worrying about).
1. Symmetry / alignment
1. Increased flexibility (it may be useful for e.g. sequencing governance actions to be able to create plans further into the future than `now + delay`)

**Comment by gbalabasquer** [comment]
@xwvvvvwx exactly. This issue was introduced with the change of the interface including the time in `plan`. Without it, we could simplify the deployment scripts also, removing the need of this deployer proxy.

**Comment by levity** [comment]
@xwvvvvwx What about modifying `plan` so it sets `era` to `add(now, delay)` if `era` is passed in as 0? This would work for us on the JS side because we would just read the logs from the tx receipt to figure out what the final value of `era` was, to use it in the `exec` call. Not sure if it's easy for `seth` as well.

**Comment by d-xo** [comment]
That feels a little awkward to me @levity, I would prefer to be more explicit. I think I would either add an overload (`plan(usr, fax)`) that sets `era` to `add(now, delay)` or just remove `era` from the interface to plan entirely.

I still want to think through the implications re: replay attacks, but I'll try and get a PR up this week.

**Comment by d-xo** [comment]
PR here: https://github.com/dapphub/ds-pause/pull/22

**Pull request merged**
