### PR TITLE
Track nonces

### PR DESCRIPTION
**Pull request by andy8052**
I worked on this with Gonzalo. This is our initial implementation of tracking nonces manually. The scripts now have to be called with `source` so that the exporting of the nonce after each call is correctly propagated through the script.

### CODE REVIEW

**Review by gbalabasquer — APPROVED** [review]

**Comment by asymmetric** [comment]
Does it need `source` so that the `export`s are propagated in the calling shell?

**Comment by andy8052** [comment]
> Does it need `source` so that the `export`s are propagated in the calling shell?

Yeah without it the exports would only keep updated until the end of each child script

**Comment by asymmetric** [comment]
Can we close this (for now)?

**Comment by gbalabasquer** [comment]
Hmm no let's merge it. Well we need to solve the conflicts. I can do it later when I finish some other stuff.
Regardless the testnet election this is a change that makes the script more robust.

**Comment by asymmetric** [comment]
Have we ever had nonce issues outside Görli? If not i'd avoid merging this, as it also makes the scripts more verbose and cluttered.

**Comment by gbalabasquer** [comment]
Using async calls yes, it happens. That is why `deploy-fab` always had the manual nonces.
I don't know, I think this change it is an improvement that makes the script resilient to fail in case for any reason the nonce could not have been correctly updated but also get your point.

**Comment by gbalabasquer** [comment]
Closing as there are no more scripts in this repo.

**Pull request closed without merging**
