### PR TITLE
Spot file pip what

### PR DESCRIPTION
**Pull request by kmbarry1**
Upgrades to the latest `dss` and fixes the call set a `pip` on the Spotter to include a `what` argument.

### CODE REVIEW

**Review by gbalabasquer — APPROVED** [review]
Looks good. I'm merging it.

**Comment by gbalabasquer** [comment]
Actually there was something missing, which I usually forget. Each time a dependency in this repo or `dss-deploy-scripts` is updated, we need to also update the `dapp.nix` file.

**Comment by kmbarry1** [comment]
Thanks for updating the file; is that a manual process or is there some command I should have run to do that?

**Comment by gbalabasquer** [comment]
Running this `nix run -f https://github.com/icetan/dapp2nix/tarball/master -c dapp2nix nix/dapp.nix` you will get the file updated with your current local submodules. So you need to make sure to have them updated before executing it.

**Pull request merged**
